### ISSUE TITLE
make/pdflatex fails on MacOS

### ISSUE THREAD

**Issue by mnwsth** [jsysresearch/template#1]
Hi,
A clone of the repo followed by make in the root dir fails on MacOS with the following error:

<code>
<recently read> \BeforeBeginEnvironment 
                                        
l.45 \BeforeBeginEnvironment
                            {tabular}{\small}

</code>

Any USENIX style file dependencies that we should be aware of?

**Comment by vijay03** [comment]
Oops, thanks for catching this! @romain-jacob identified the dependency and I've added it -- can you pull the latest version and see if that resolves it?

**Comment by mnwsth** [comment]
Works now. Thanks much.
